name: vlone_blog_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  go_router: ^16.2.5
  get_it: ^8.2.0
  supabase_flutter: ^2.10.3
  image_picker: ^1.2.0
  video_player: ^2.10.0
  cached_network_image: ^3.4.1
  workmanager: ^0.9.0+3
  intl: ^0.20.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.5.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  share_plus: ^12.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
